name: Pipeline

on:
  push:
    paths:
      - "05_pipeline/**"
  pull_request:
    paths:
      - "05_pipeline/**"
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: Install requirements
        run: pip install --quiet --requirement ./05_pipeline/requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py
      - name: Run unit tests
        run: |
          cd 05_pipeline/
          python -m unittest --verbose --failfast
