name: Pipeline

on:
  push:
    paths:
      - "05_pipeline/**"
  pull_request:
    paths:
      - "05_pipeline/**"
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
      - name: Install requirements
        run: pip install --quiet --requirement ./05_pipeline/requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 ./05_pipeline/*.py
          pylint --disable=C0301 --disable=C0326 ./05_pipeline/*.py
      - name: Run unit tests
        run: |
          cd 05_pipeline/
          python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./05_pipeline/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APPLICATION_NAME }}:latest

  test_image:
    needs: [build_image]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run unit tests in container
        run: docker run "${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APPLICATION_NAME }}:latest" -m unittest --verbose --failfast
